name: Build and deploy to production

on:
  push:
    # branches:
    #   - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: yarn install --forzen-lockfile
      - run: yarn build
      - name: Upload build artifact
        uses: actions/upload-artifact@master
        with: &build_artifact
          name: dist
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Download build artifact
        uses: actions/download-artifact@master
        with: *build_artifact
      - run: ls dist
